#!/usr/bin/env bash
# Bash script that loops from 1 to 10

counter=1
while [ $counter -ne 11 ]
do
  if [ $counter -eq 4 ]
  then
    echo "Bad luck"
  elif [ $counter -eq 8 ]
  then
    echo "Good luck"
  else
    echo "Best School"
  fi
  ((counter++))
done