#!/usr/bin/env bash
# Retrieve all IPv4 addresses
ip_addresses=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d '/' -f1)
 # Display each IPv4 address
for ip in $ip_addresses
do
    echo $ip
done